//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisClubNeu
{
    using System;
    using System.Collections.Generic;
    
    public partial class GridInfo
    {
        public int Id { get; set; }
        public int PlatzId { get; set; }
        public int Rows { get; set; }
        public int Columns { get; set; }
        public int SpaceColumnWidth { get; set; }
        public int SpaceRowHeight { get; set; }
        public int ContentColumnWidth { get; set; }
        public int ContentRowHeight { get; set; }
        public string PositionsRow { get; set; }
        public string PositionsColumn { get; set; }
    }
}
