//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisClubNeu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TennisclubNeuEntities : DbContext
    {
        public TennisclubNeuEntities()
            : base("name=TennisclubNeuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buchungen> Buchungen { get; set; }
        public virtual DbSet<Plätze> Plätze { get; set; }
        public virtual DbSet<PlatzInBearbeitung> PlatzInBearbeitung { get; set; }
        public virtual DbSet<Platzsperre> Platzsperre { get; set; }
        public virtual DbSet<Spieler> Spieler { get; set; }
        public virtual DbSet<SpielerInBearbeitung> SpielerInBearbeitung { get; set; }
        public virtual DbSet<GridInfo> GridInfo { get; set; }
    }
}
